apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-rwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-rwo
  template:
    metadata:
      labels:
        app: test-rwo
    spec:
      containers:
        - name: test-rwo
          image: nginx
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: volume-rwo
      volumes:
        - name: volume-rwo
          persistentVolumeClaim:
            claimName: pvc-rwo
