apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-rwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rwo
  template:
    metadata:
      labels:
        app: nginx-rwo
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: volume-rwo
      volumes:
        - name: volume-rwo
          persistentVolumeClaim:
            claimName: pvc-rwo
