apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-rwop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rwop
  template:
    metadata:
      labels:
        app: nginx-rwop
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: volume-rwop
      volumes:
        - name: volume-rwop
          persistentVolumeClaim:
            claimName: pvc-rwop
