apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: python-container
      image: quando2299/simple-python-app:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: db-config-json
