apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8s-configuration
  name: {{ .Values.configmap.name }}
data:
  db-config.json: |
    {
      "database_host": "localhost",
      "database_port": 5432
    }